name: Daily Report Bot

on:
  schedule:
    - cron: '0 5 * * *'  # 08:00 МСК (UTC+3)
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Report Bot
      env:
        REPORT_PORTAL_USERNAME: ${{ secrets.REPORT_PORTAL_USERNAME }}
        REPORT_PORTAL_PASSWORD: ${{ secrets.REPORT_PORTAL_PASSWORD }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py